### ISSUE TITLE
P5 data trail path segmentation feature implementation

### ISSUE THREAD

**Issue by edw1nzhao** [BenRydal/igs#43]
Implement the feature in Svelte that allows for the segmentation of data trails/path in P5.

## Acceptance Criteria

- [ ] Data trails should be properly segmented based on predefined criteria.
- [ ] The segmented paths should be displayed accurately in the UI.

**Comment by BenRydal** [comment]
To clarify, this refers to migrating what are known as "code files" and ways they are both processed when loaded and also how they influence the display of paths. There are some intricacies with how code segments impact movement path drawing in DrawMovement classes that I should be able to help a lot with.

**Comment by BenRydal** [comment]
@edw1nzhao working on this now. Beginning by refactoring core class

**Comment by edw1nzhao** [comment]
![Image](https://github.com/BenRydal/igs/assets/21957329/e7278fa7-a016-4a9f-a004-cda06c7fc785)

**Comment by edw1nzhao** [comment]
![Image](https://github.com/user-attachments/assets/54e5a304-1768-4be4-a9ae-777e8fcaa22d)

Colour by codes is implemneted now as the default and first tab in each user.
