### ISSUE TITLE
Validating the loading of custom CSV files as they come in

### ISSUE THREAD

**Issue by edw1nzhao** [BenRydal/igs#44]
Implement a validation mechanism to ensure that the custom CSV files being uploaded are properly formatted and contain the necessary data for the application.

## Acceptance Criteria

- [ ] The system should validate the file format to ensure it is a CSV.
- [ ] The system should check for specific headers or data types that are expected in the CSV.
- [ ] Display an error message if the validation fails.
- [ ] Successfully load the CSV into the application if validation passes.

**Comment by BenRydal** [comment]
Completed. Integrated older csv file tests into validation. In the future, explore external library to replace existing validation tests.

**Comment by edw1nzhao** [comment]
https://github.com/users/BenRydal/projects/1?pane=issue&itemId=44301218

Reference this for future work.
