### ISSUE TITLE
Migrate Video Player feature

### ISSUE THREAD

**Issue by edw1nzhao** [BenRydal/igs#45]
Migrate the existing Video Player functionality from the traditional HTML, CSS, and JavaScript stack to a Svelte component.

## Acceptance Criteria

- [ ] The video player should have similar or improved UI/UX in Svelte.
- [ ] All existing functionalities (play, pause, seek, etc.) should work as expected.
- [ ] Video sources should be loaded dynamically.

**Comment by BenRydal** [comment]
Before doing this let's chat after we both review the current codebase, but if helpful, there is a video controller (in the video folder) that allows you to create different kinds of video players. Currently you can create a YouTube player (plays YouTube videos) or a p5 player (which uses p5 methods to support displaying user loaded videos). In the future, the idea is you could add lots of different players, but YouTube and p5 player are all we need now. This may actually be a fairly simple thing to address and we might not really need to "migrate" much---just updating buttons in the interface that call the Video Controller class to do things like show/hide video

**Comment by edw1nzhao** [comment]
@BenRydal will work on this to get the video sync'd up
