### ISSUE TITLE
Pull logic within the page.svelte under sketch to be in a library instead

### ISSUE THREAD

**Issue by edw1nzhao** [BenRydal/igs#49]
Refactor the code in page.svelte that falls under sketch and move it into a separate library for better modularity.

## Acceptance Criteria

- [ ] All functionalities should remain intact after the refactor.
- [ ] page.svelte should be cleaner and more focused.
- [ ] The new library should be easily importable and usable within page.svelte.

**Comment by BenRydal** [comment]
This will be super helpful just to step back and see things as well.
